### ISSUE TITLE
Trying to send to Office365 throws TLS error

### ISSUE THREAD

**Issue by shaxraman** [decke/smtprelay#1]
Hi

Looks like a great utility, exactly what I was looking for, but I ran into a snag trying to send email to Office365:

Config file:

remote_host = smtp.office365.com: 587

`2020/05/14 13:47:41 delivering using smarthost smtp.office365.com:587
2020/05/14 13:47:52 delivery failed: 504 5.7.4 Unrecognized authentication type [HE1PR0401CA0078.eurprd04.prod.outlook.com]`

Am using an application password for the authentication, but also tried with a non-MFA account - same error.

**Comment by grffio** [comment]
You need to use the `Login` auth mechanism, the solution is described [here](https://gist.github.com/andelf/5118732).
You can add the configuration flag `LoginAuthType: false/true`, and check it, depending on the flag use `Login` or `Plain` [auth mechanism](https://github.com/decke/smtprelay/blob/2afbe674073123b7177df61d2c3475ceb1007879/main.go#L113).

**Comment by decke** [comment]
I will have a look at it. Looks like it should be easy to fix.

**Comment by decke** [comment]
Should be working now. You will need to set remote_auth = login in your smtprelay.ini to test it.
