### ISSUE TITLE
Errors returned by smtpd.Server.ListenAndServe() are ignored

### ISSUE THREAD

**Issue by JonathonReinhart** [decke/smtprelay#10]
# Problem
Any errors returned by `ListenAndServe()` are ignored.

For example, trying to run as an unprivileged user:
```
$ ./smtprelay -logfile smtprelay.log
2021/02/15 01:03:28 Listen on 127.0.0.1:25 ...
2021/02/15 01:03:28 Listen on [::1]:25 ...
```
The server runs and looks like it is listening, but it is is not (because binding to port 25 is a privileged operation). This is confirmed by looking at `lsof -p $(pidof smtprelay)` or `ss -tnlp`.

# Cause
The cause is simple: [`ListenAndServe()` is invoked as a goroutine](https://github.com/decke/smtprelay/blob/0e8986ca79f94792343d93027ff28352bd1c212c/main.go#L259) and the return value is lost.

**Comment by decke** [comment]
Thanks for the fix!
