### ISSUE TITLE
Passwords with /

### ISSUE THREAD

**Issue by pgilgunn** [decke/smtprelay#101]
Hi

I am looking to use this for AWS SES integration, as it looks like a good fit. Unfortunately, all the SES-generated passwords contain "/" in the password, and this is not handled well. Do you have any suggestions for this?

Config
remotes = starttls://username:pass/word@email-smtp.2.amazonaws.com:587

Error message
 level=fatal msg="error parsing url: 'starttls://username:pass/word@email-smtp.2.amazonaws.com:587': parse \"starttls://username:pass/word@email-smtp.2.amazonaws.com:587\": invalid port \":pass\" after host" remotes="starttls://username:pass/word@email-smtp.2.amazonaws.com:587"

Thanks

**Comment by decke** [comment]
`pass/word` should be `pass%2Fword`

**Comment by pgilgunn** [comment]
Thanks dercke that worked perfectly.
