### ISSUE TITLE
Consider doing a new release

### ISSUE THREAD

**Issue by fblz** [decke/smtprelay#120]
I guess most people will not build this from master and thus not benefit from the dependency updates over the last year.
You may consider doing a new release build.

**Comment by decke** [comment]
Yeah I can do that. There is only one real commit since the last release so it looks like the project is finally at a stage where it does work for most people so there is not much development going on right now.

**Comment by decke** [comment]
Release 1.10.0 is available. It was a good exercise to find some hidden issues with the CI and Release actions and Go 1.20.
