### ISSUE TITLE
empty body

### ISSUE THREAD

**Issue by ryanburnette** [decke/smtprelay#122]
I have a use case where an older copy machine sends its scans via smtp and I am using smtprelay for that purpose. My email delivery API doesn't accept an empty body, which the copy machine tries to send, so I have a fork that adds the body. I am also adding some headers to prevent the messages from threading even though they have the same subject.

I was wondering if features like default body or append to body, or default subject or append to subject would be useful to anyone else or valuable in a PR.

**Comment by decke** [comment]
Can you show me some code for this? If it's not too intrusive I think it can be useful also in other cases.
