### ISSUE TITLE
Feature Request: Customizable User-Agent Header in smtprelay

### ISSUE THREAD

**Issue by erseco** [decke/smtprelay#131]
Hello,

We are using your `smtprelay` software and have recently run into a challenge with certain servers that block the connection based on the `User-Agent` header. We've identified that the connection is being blocked because the recipient server doesn't recognize or accept the default user-agent our software is sending.

To overcome this limitation, we'd like to request a feature where we can customize the `User-Agent` header in `smtprelay` to simulate being another email client, thus improving our email deliverability. 

For instance, we'd like to set our user-agent to mimic Thunderbird:
```
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Thunderbird/91.8.0
```

Being able to modify the `User-Agent` would provide us (and potentially other users of your software) with more flexibility and better deliverability when dealing with servers that have stringent rules on client identification.

We appreciate your consideration of this feature request and look forward to any feedback or updates.

Best regards!

**Comment by decke** [comment]
Modifying the content / headers of a mail is definitely out of scope for smtprelay.
