### ISSUE TITLE
Issue warning if configured to require authentication but not TLS

### ISSUE THREAD

**Issue by JonathonReinhart** [decke/smtprelay#26]
`smtpd` [only allows authentication if the session is operating with TLS](https://github.com/chrj/smtpd/blob/v0.3.0/smtpd.go#L415-L417):

```go
	if session.server.Authenticator != nil && session.tls {
		extensions = append(extensions, "AUTH PLAIN LOGIN")
	}
```

This is probably a safe requirement.

However, the following configuration will never work:
```
$ ./smtprelay -listen ':2525' -allowed_users userlist.txt
```

If authentication is required (`-allowed_users`), then a `-listen` w/o `tls://` or `starttls://` should be forbidden.

**Comment by decke** [comment]
Yeah that is true and it is to avoid sending authentication credentials over an unencrypted channel. So this combination does not make sense and we should make a small note in the config text that allowedUsers requires encrypted channel and error out early if this combination is used.
