### ISSUE TITLE
Hook to scan with rspamd or similar via HTTP

### ISSUE THREAD

**Issue by mikeburgh** [decke/smtprelay#35]
Hi,

Any interest in a PR to allow a scan of the email via a HTTP post to an external agent ?

I have been looking for a while for a simple relay smtp that has the ability to virus scan/spam filter the emails before relaying (not accepting to a local queue and then forwarding). Currently using haraka, but this feels like a cleaner, less complex solution so might have a go at adding it in as a config option

**Comment by decke** [comment]
Yeah, definitely interested in that.

A question was raised some time ago if smtprelay could also handle incoming emails from the internet and forward to a single address. The main concern was that there is no spam filtering right now and rspamd looks like a decent solution for that.

**Comment by mikeburgh** [comment]
Sorry about not getting back to you.. ended up getting what I needed working in postfix, so for now sticking with that.
