### ISSUE TITLE
add options passed to smtpd

### ISSUE THREAD

**Issue by ryanburnette** [decke/smtprelay#37]
The smtpd dependency has some configurable options. I have the need to configure MaxConnections, for example. smtprelay.ini should probably include the ability to configure all or most of the options that can be passed to smtpd. I'd be happy to PR if you'd like.

**Comment by electron0zero** [comment]
we also needed these, and added them in https://github.com/grafana/smtprelay/pull/19

happy to send it to upstream :)

**Comment by Coronon** [comment]
Was there any work done on this? I require ‘MaxConnections’ and would probably be able to hand in a PR this evening (CET).
