### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by sunshine69** [decke/smtprelay#44]
Just go `go build .` in the root and got

azureuser@stevek-playground 12:50 ~/s/smtprelay master> go mod tidy
go: github.com/chrj/smtpd@v0.3.0 requires
	github.com/eaigner/dkim@v0.0.0-20150301120808-6fe4a7ee9cfb: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/azureuser/go/pkg/mod/cache/vcs/b1a9951edebf25b789a34398ad65880e06631bf718a381c881083257167b44d8: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
go: github.com/chrj/smtpd@v0.3.0 requires
	github.com/eaigner/dkim@v0.0.0-20150301120808-6fe4a7ee9cfb: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/azureuser/go/pkg/mod/cache/vcs/b1a9951edebf25b789a34398ad65880e06631bf718a381c881083257167b44d8: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled

Not having time to look at it though but better the author should make sure it builds nicely, given that it is golang, building mod is pretty much straight forward.

**Comment by alex1989hu** [comment]
FYI: created a PR <https://github.com/chrj/smtpd/pull/13> to address the issue
