### ISSUE TITLE
I get an error message re. SSL when connecting to remote the remote service

### ISSUE THREAD

**Issue by quistian** [decke/smtprelay#5]
# swaks -s 10.10.10.11 --to russ@quist.ca
=== Trying 10.10.10.11:25...
=== Connected to 10.10.10.11.
<-  220 localhost.localdomain ESMTP ready.
 -> EHLO localhost
<-  250-localhost.localdomain
<-  250-SIZE 10240000
<-  250-8BITMIME
<-  250 PIPELINING
 -> MAIL FROM:<root@localhost>
<-  250 Go ahead
 -> RCPT TO:<russ@quist.ca>
<-  250 Go ahead
 -> DATA
<-  354 Go ahead. End your data with <CR><LF>.<CR><LF>
 -> Date: Thu, 03 Dec 2020 15:55:24 -0500
 -> To: russ@gmail.org
 -> From: root@localhost
 -> Subject: test Thu, 03 Dec 2020 15:55:24 -0500
 -> Message-Id: <20201203155524.042117@localhost>
 -> X-Mailer: swaks v20190914.0 jetmore.org/john/code/swaks/
 ->
 -> This is a test mailing
 ->
 ->
 -> .
<** 554 Forwarding failed
 -> QUIT
<-  221 OK, bye

And the log file says:
2020/12/03 15:55:24 new mail from=<root@localhost> to=[russ@gmail.org peer=[10.10.10.11]
2020/12/03 15:55:24 delivering using smarthost smtp.mailgun.org:587
2020/12/03 15:55:24 delivery failed: x509: certificate signed by unknown authority

Have I got something misconfigured?

**Comment by decke** [comment]
Sounds like Go is unable to verify the CA so I would start checking what openssl says:

`openssl s_client -host smtp.gmail.com -port 587 -starttls smtp -crlf`

**Comment by quistian** [comment]
Many thanks.

Russell P. Sutherland            Email: russell.sutherland@utoronto.ca
Network Engineer, I+TS       Voice: +1.416.978.0470
4 Bancroft Ave., Rm. 102      Cell: +1.416.803.0080
University of Toronto
Toronto, ON  M5S 1C1

________________________________________

**Comment by decke** [comment]
Did you have time to check if that worked or is the issue still relevant?
