### ISSUE TITLE
Docs please.

### ISSUE THREAD

**Issue by amarjeetanandsingh** [decke/smtprelay#57]
Hi, 
Thanks for the wonderful piece of code.
But adding some documentation on how to build/deploy/config in the README.md is good to have.

**Comment by decke** [comment]
Don't know what you expect but it's really simple. You can either use the binaries from the release or use `go build` to compile a binary yourself. Deployment needs to copy smtprelay binary and the smtprelay.ini. Configuration is done in the INI file. Parameters are described there.

**Comment by amarjeetanandsingh** [comment]
thanks decke
