### ISSUE TITLE
Add metrics exposition

### ISSUE THREAD

**Issue by pomverte** [decke/smtprelay#62]
Hello,

Do you have any plan to support metrics expostion in openmetrics format ?

Are you open to contribution ?

That would allow monitoring services like Prometheus to scrape metrics

Reference : https://prometheus.io/docs/guides/go-application/

**Comment by JonathonReinhart** [comment]
@grafana has [a fork](https://github.com/grafana/smtprelay) where they added metrics for prometheus: https://github.com/grafana/smtprelay/pull/9/. They attempted to upstream all of their changes in #13, but it wasn't organized in a way we were willing to accept. In [this comment](https://github.com/decke/smtprelay/pull/13#issuecomment-797957014) I explained how I fixed up most of their work into individual PRs, but the Prometheus exporter was not included.

I'll let @decke confirm that he is willing to accept this feature. You may want to look at https://github.com/grafana/smtprelay/pull/9/ to avoid unnecessary work, and increase coherency within the network of forks.

cc @electron0zero @dannykopping

**Comment by decke** [comment]
It's fine for me but since I don't use prometheus myself I likely won't notice if we break it one day.

**Comment by decke** [comment]
smtprelay does not store and forward if that is your question. It forwards directly so retry is needed on the sending side.
