### ISSUE TITLE
Password with special characteres

### ISSUE THREAD

**Issue by whiiiskyy** [decke/smtprelay#74]
Hi guys,

After creating a Dockerfile to run the latest `smtprelay`, I got everything working using a Gmail account with 2FA and an app password.

The problem tho comes when the password has special characters on it.
I am having some issues working that out.

Removing the special characters from the password, it starts.
I have tried that basic scapes I know but got nowhere: ", ', \, %

I am running it like this ` smtprelay -config /etc/smtprelay/smtprelay.ini `(currently working with Gmail and App password(2FA))
I need to solve the above to get it working with Office365.

How can I solve this?

Thank you

**Comment by whiiiskyy** [comment]
I managed to get it started by encoding the special characters like replacing `@` with `%40` for example
It starts without problem but when sending an email:

`ERRO[2022-06-09T04:21:31Z] delivery failed err_code=504 err_msg="5.7.4 Unrecognized authentication type [XXXXXXXXX.prod.outlook.com]"`

**Comment by decke** [comment]
There isn't much I can help with since I don't care much about Docker nor Microsoft products.

Probably it helps to let you know that we don't do anything with the password so it's just used and passed as it is.

**Comment by decke** [comment]
For authentication you could try if they support LOGIN auth.

https://github.com/decke/smtprelay/blob/master/smtprelay.ini#L102

**Comment by whiiiskyy** [comment]
@decke thank you for the reply and sorry for the delay on this. Got carried away with other tasks.
Good to know it passes as it's, I will have a look around.

For the matter, I am not into Microsoft either but I cannot escape Docker and Kubernetes. 
Either way, I got it working just fine with both. I am lost with the way how it uses variables tho. 
In case it is something you could point me in the right direction: https://github.com/decke/smtprelay/issues/81

Thank you for the help. I am closing this.
