### ISSUE TITLE
Cannot use settings from ini file

### ISSUE THREAD

**Issue by cristianlivella** [decke/smtprelay#79]
I don't know if I am doing something wrong, but it seems that reading the configuration from the ini file doesn't work.

If I try to run smtprelay with `./smtprelay -config smtprelay.ini`, execution ends immediately without any output.

Maybe there is something wrong with reading files, because the `-logfile` parameter also seems not to work.

Tried on Fedora 33 and Raspbian 9.9, builded with go1.18.3.

**Comment by whiiiskyy** [comment]
That is weird, it has to work.
This is how I run it: 
Docker/Kubernetes containers: `"/usr/local/bin/smtprelay", "-config", "/etc/smtprelay/smtprelay.ini", "/var/log/smtprelay.log"`
Terminal: `/usr/local/bin/smtprelay -config /etc/smtprelay/smtprelay.ini`

Then I check the log file set with `-logfile`

**Comment by ghuntley** [comment]
> When specifying a (valid) file with -config, the program just ends with no output.

Confirmed; returns RC=1

**Comment by decke** [comment]
Thanks for the reports, it should be fixed now!
