### ISSUE TITLE
i cant seem to use "#" <- this kind of special ascii character as password.

### ISSUE THREAD

**Issue by hiqsociety** [decke/smtprelay#89]
error parsing url: 'starttls://abc@example.com:587': parse "starttls://abc@example.com:ofy#": invalid port ...

**Comment by decke** [comment]
Cannot reproduce. You seem to use an invalid format. Format is:

protocol://[user[:password]@][netloc][:port][/remote_sender][?param1=value1&...]

so it should be:

starttls://abc:ofy#@example.com:587

**Comment by hiqsociety** [comment]
can you try this? i think there's an issue with the pipe "|" character etc. the below are the characters used as legit password

remotes = starttls://no-reply@example.com:okf#|Qd&3r%4A]fdy#4@example.com:587

**Comment by vipsland** [comment]
hi, any feedback on this?

**Comment by hiqsociety** [comment]
hi, any feedback on this?

**Comment by decke** [comment]
We are using Go url.Parse() for this so you can try to urlencode your special characters in the password.

**Comment by hiqsociety** [comment]
ok thx
