### ISSUE TITLE
remotes depends on from

### ISSUE THREAD

**Issue by szonov** [decke/smtprelay#91]
Is it possible to configure  several remotes and use it depends on from address?

For example I have to emails first@gmail.com and second@hotmail.com, 
and I want if from is first@gmail.com it should be sent over smtp.gmail.com, but if from address second@hotmail.com it should be send over smtp.hotmail.com.

**Comment by decke** [comment]
No it is not possible yet and I think it's also not in scope for smtprelay.

**Comment by szonov** [comment]
ok, thank you

**Comment by szonov** [comment]
@decke it is possible to use my idea for it?
look at my commit above

**Comment by decke** [comment]
The commit looks okay to me. Can you please create a pull request for it?

**Comment by szonov** [comment]
> The commit looks okay to me. Can you please create a pull request for it?

done
