### ISSUE TITLE
(X)OAUTH2 support

### ISSUE THREAD

**Issue by Enrico204** [decke/smtprelay#96]
Are you willing to add support OAUTH2/XOAUTH2? It's an authentication for SMTP, based on OAuth2. Google uses it, as well as other providers.

My use case: I have some devices (printer, router, etc.) that support only standard SMTP authentication, and I want to use a Google e-mail address to send e-mails. This can be done either by using a device-specific password (but this requires a 2-step authentication) or `XOAUTH2` method.

I'm testing some modifications to `smtprelay` to add support for this. Basically, there is another small program that is used to get access and refresh tokens from Google (in theory, that should be done only once, when configuring `smtprelay`) and then I added a new "authenticator" in the SMTP client to support this (in addition to plain and login).

I'll push my modifications in a public repository as soon as I have some time :-) In the meantime, I'm testing/debugging it.

**Comment by decke** [comment]
This is a very Google specific issue and I recommend to continue using their "App passwords" feature with a dedicated account for SMTP. Yes, this might require 2nd factor on that account and probably they disable this feature some day but for the moment this OAUTH2 dance is a pain without any security benefit if you use a dedicated account.

As a general rule of thumb I would always recommend to avoid Google.

**Comment by Enrico204** [comment]
Actually, this is not a Google-specific issue, because other big cloud providers are following the same path.

However, I totally understand your decision, and I stand with your suggestion of avoiding Google.

The reason for doing this is that I have no choice but using this method (unfortunately). I'll maintain my own fork, then :-)

**Comment by decke** [comment]
As a followup I could find Office 365 / Microsoft and Google which seem to support it. Then I also found [simonrob/email-oauth2-proxy](https://github.com/simonrob/email-oauth2-proxy) which looks like a transparent XOAUTH2 proxy according to the project description.
