### ISSUE TITLE
Provide a Dockerfile

### ISSUE THREAD

**Issue by mreiche** [decke/smtprelay#97]
Hi.

I'm using the Fork grafana/smtprelay as container, but their version is just outdated, which doesn't support accepting untrusted remote tls certs.

I would like to copy their Dockerfile and provide it here, to prevent even more forks.

What are your thinking about that? What are your thinking about publishing an official decke/smtprelay image?

Best,
Mike

**Comment by decke** [comment]
I currently do not plan to provide any Docker images and support for it myself. Please see #54 , #50 and #85.
